### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageCode = "en"
  #languagePrefix = ""
  #timeZone = "Etc/UTC"
  #weight = 110
  #[en.params]
    #languageCodeCountry = "DO_NOT_USE"
    #languageFlag = "ğŸ‡¬ğŸ‡§"

[en-ph]
  languageName = "English (PH)"
  languageCode = "en-PH"
  #languagePrefix = ""
  timeZone = "Asia/Manila"
  weight = 111
  [en-ph.params]
    languageCodeCountry = "ph"
    languageFlag = "ğŸ‡µğŸ‡­"
  [[en-ph.menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [en-ph.menu.main.params]
      newTab = false

#[fil]
  #languageName = "Filipino"
  #languageCode = "fil"
  #languagePrefix = ""
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #languageCodeCountry = "ph"
    #languageFlag = "ğŸ‡µğŸ‡­"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageCode = "tl-Tglg"
  #languagePrefix = ""
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #languageCodeCountry = "ph"
    #languageFlag = "ğŸ‡µğŸ‡­"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageCode = "zh-Hant"
  #languagePrefix = ""
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #languageCodeCountry = "cn"
    #languageFlag = "ğŸ‡¨ğŸ‡³"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageCode = "zh-Hans"
  #languagePrefix = ""
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #languageCodeCountry = "cn"
    #languageFlag = "ğŸ‡¨ğŸ‡³"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageCode = "ja"
  #languagePrefix = ""
  timeZone = "Asia/Tokyo"
  weight = 140
  title = "YourOnly.Oneã®Hugoãƒ†ã‚¹ãƒˆã‚µã‚¤ãƒˆ"
  [ja.params]
    languageCodeCountry = "jp"
    languageFlag = "ğŸ‡¯ğŸ‡µ"
    description = "YourOnly.Oneã®Hugoãƒ†ã‚¹ãƒˆã‚µã‚¤ãƒˆ"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[ja.menu.main]]
    name              = "ãƒ›ãƒ¼ãƒ "
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ja.menu.main.params]
      newTab = false

[ko]
  languageName = "í•œêµ­ì–´"
  languageCode = "ko"
  #languagePrefix = ""
  timeZone = "Asia/Seoul"
  weight = 150
  title = "YourOnly.One's Hugo í…ŒìŠ¤íŠ¸ ì‚¬ì´íŠ¸"
  [ko.params]
    languageCodeCountry = "kr"
    languageFlag = "ğŸ‡°ğŸ‡·"
    description = "YourOnly.One's Hugo í…ŒìŠ¤íŠ¸ ì‚¬ì´íŠ¸"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[ko.menu.main]]
    name              = "ì§‘"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ko.menu.main.params]
      newTab = false
